spring:

  # h2 인메모리 DB 설정
  h2:
    console:
      enabled: true
      path: /h2-console

  # JDBC 설정
  datasource:
    url: 'jdbc:h2:mem:testdb'
    username: sa
    password:

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  # OAuth
  profiles:
    include: real # application-oauth.yml 을 참조 함

  # Session Store
  session:
    store-type: jdbc

  #
  pid:
    file: /home/ec2-user/app/step2/springboot2-aws.pid

